---
permissions:
  contents: write

concurrency:
  group: publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5

      - uses: goreleaser/goreleaser-action@v6
        with:
          install-only: true

      - env:
          GH_TOKEN: ${{ github.token }}
        run: |-
          make ci
